# This is a basic workflow that is manually triggered

name: Build OpenCV

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      opencv-download-url: 'https://github.com/opencv/opencv/archive/4.2.0.zip'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Cache OpenCV source code download
      id: opencv-source-cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: opencv.zip
        # An explicit key for restoring and saving the cache
        key: opencv-source-cache-${{ env.opencv-download-url }}
    - name: Download on Unix
      if: steps.opencv-source-cache.outputs.cache-hit != 'true' && !contains(matrix.os, 'windows')
      run: wget -q -O opencv.zip ${{ env.opencv-download-url }}
    - name: Download on Windows
      if: steps.opencv-source-cache.outputs.cache-hit != 'true' && contains(matrix.os, 'windows')
      run: Invoke-WebRequest ${{ env.opencv-download-url }} -OutFile opencv.zip
