# This is a basic workflow that is manually triggered

name: Build OpenCV

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      opencv-download-url:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'OpenCV Download URL'
        # Default value if no value is explicitly provided
        default: 'https://github.com/opencv/opencv/archive/4.2.0.zip'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  getting_source_code:
    runs-on: ubuntu-latest
    steps:
    - name: Download on Unix
      run: wget -q -O opencv.zip ${{ github.event.inputs.opencv-download-url }}
    - name: Unzip source code
      run: unzip -q opencv.zip
    - name: Rename extracted folder
      run: mv opencv-* opencv/
    - uses: actions/upload-artifact@v2
      with:
        name: opencv-source-code
        path: opencv/
